### ISSUE TITLE
Disable Humidity doesn't work

### ISSUE THREAD

**Issue by Kepete** [ingowalther/homebridge-advanced-http-temperature-humidity#2]
I need to disable humidity but this doesn't work. 
`
"accessory": "AdvancedHttpTemperatureHumidity",
"name": "Temp",
"url": "http://192.168.x.xx/"
"http_method": "GET",
"disableHumidity": true
`
On the older plugin it worked fine, but the older crashes Homebridge when connection error

**Comment by ingowalther** [comment]
Hello @Kepete,

I fixed this issue in Version "1.0.1". Please try using the new version.

Greetings Ingo

**Comment by Kepete** [comment]
Thank you for you support @ingowalther 

I just updated to version 1.0.1, rebooted the system and also removed the homebridge accessories cached fail. 
Still `"disableHumidity": true` doesn't work.

**Comment by Kepete** [comment]
My phone somehow didn't update the home app accessorise. Now everything work. Thanks!

**Comment by ingowalther** [comment]
You are welcome. Great to hear that.

Greetings
