### ISSUE TITLE
Wrong plugin identifier reported in the HomeBridge log

### ISSUE THREAD

**Issue by horodchukanton** [ingowalther/homebridge-advanced-http-temperature-humidity#4]
Got this in the HomeBridge (Version 1.1.1) log
`[8/7/2020, 3:21:36 PM] ---`
`[8/7/2020, 3:21:42 PM] Loaded plugin: homebridge-advanced-http-temperature-humidity@1.0.1`
`[8/7/2020, 3:21:42 PM] Plugin 'homebridge-advanced-http-temperature-humidity' tried to register with an incorrect plugin identifier: 'homebridge-advancedhttptemperaturehumidity'. Please report this to the developer!`
`[8/7/2020, 3:21:42 PM] Registering accessory 'homebridge-advanced-http-temperature-humidity.AdvancedHttpTemperatureHumidity'`
`[8/7/2020, 3:21:42 PM] ---`

**Comment by ingowalther** [comment]
Should be fixed in Version 1.0.2
